apiVersion: v1
data:
  init.sql: "CREATE DATABASE db_ms;\n\n\\c db_ms;\n\nCREATE TABLE IF NOT EXISTS T_USER( \n\n    id SERIAL PRIMARY KEY,\n    email VARCHAR(30) UNIQUE,\n    password VARCHAR(30)\n);\n\nINSERT INTO TABLE T_USER ('esisa@esisa.ac.ma', 1234);\n\nINSERT INTO TABLE T_USER ('test@esisa.ac.ma', 1234);"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db
  name: db-cm0
